# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  #push
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

  # # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "UnitTest"
  UnitTest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Install python3 moudle
        run: sudo apt install python3

      - name: Install pip3  moudle
        run: sudo apt install python3-pip

      - name: Install coverage module
        run: pip3 install coverage

      - name: Install python3-coverage module
        run: sudo apt install python3-coverage -y

      - name: Install pyside6 module
        run: pip3 install pyside6

      - name: Install pytest module
        run: pip3 install pytest

      - name: Install python3-pytest module
        run: sudo apt install python3-pytest -y

      - name: Install pytest-qt module
        run: pip3 install pytest-qt

      - name: Install python3-pytestqt module
        run: sudo apt install python3-pytestqt -y

      - name: Install pytest-cov module
        run: pip3 install pytest-cov

      - name: Install python3-pytest-cov module
        run: sudo apt install python3-pytest-cov -y

      - name: Install python3-pymysql module
        run: sudo apt install python3-pymysql

      - name: Install pymysql module
        run: pip3 install pymysql

      # - name: execute CI test
      #   run: sudo python3-coverage run --source='lib.PPM.PPM,PPM_window' -m pytest-3 ./test/Test_PPM.py ./test/Test_PPMWindow.py
      - name: install libxcb-xinerama0
        run: sudo apt install libxcb-xinerama0
      - name: Uninstall opencv
        run: pip uninstall opencv-python
      - name: Install opencv
        run: pip install opencv-python-headless
      - name: export DISPLAY=:0
        run: export DISPLAY=:0
      - name: export QT_QPA_PLATFORM=offscreen
        run: export QT_QPA_PLATFORM=offscreen
      - name: python3 PPM_window.py
        run: python3 PPM_window.py
      - name: execute CI test
        run: sudo pytest-3 --cov lib.PPM --cov PPM_window --cov PySide6 ./test/Test_PPM.py ./test/Test_PPMWindow.py

      # - name: Generate html(the unittest coverage of codes)
      #   run: coverage html
        
      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo Hello, world!

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
